# Generated by Django 4.1.4 on 2022-12-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_item_classificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="link_imagem",
            field=models.CharField(default="", max_length=200),
        ),
    ]
