# Generated by Django 4.1.4 on 2023-01-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_item_link_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomeTipo", models.CharField(max_length=100)),
                ("qtdCadeiras", models.PositiveIntegerField()),
                ("qtdMesas", models.PositiveIntegerField()),
            ],
        ),
    ]
